/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-05 00:59:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/member.css\">\r\n");
      out.write("<title>써브웨이</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<section>\r\n");
      out.write("		<h2>안녕하세요. Subway 회원가입 페이지 입니다.</h2>\r\n");
      out.write("		<p>회원정보를 입력해주세요.</p>\r\n");
      out.write("		<form name=\"regFrm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member\">\r\n");
      out.write("			<table class=\"form-table\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이름</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" id=\"name\" name=\"name\" required>\r\n");
      out.write("						<p class=\"error\" id=\"nameError\">이름은 한글 2자 이상 입력하세요.</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>성별</th>\r\n");
      out.write("					<td>");
      out.write("\r\n");
      out.write("						<label><input type=\"radio\" name=\"gender\" value=\"1\" checked required> 남</label>\r\n");
      out.write("						<label><input type=\"radio\" name=\"gender\" value=\"2\"> 여</label>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>휴대폰 번호</th>\r\n");
      out.write("					<td><input type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\"01012345678\" required>\r\n");
      out.write("						<p class=\"error\" id=\"phoneError\">휴대폰 번호 형식이 올바르지 않습니다.</p>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>아이디</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" id=\"id\" name=\"id\" required>\r\n");
      out.write("						<button type=\"button\" onclick=\"idCheck(this.form.id.value)\">ID 중복확인</button>\r\n");
      out.write("						<p class=\"error\" id=\"idError\">아이디는 영문·숫자 조합 8자 이상 12자리 이하입니다.</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"password\" id=\"pwd\" name=\"pwd\" required>\r\n");
      out.write("						<p class=\"error\" id=\"pwdError\">비밀번호는 영문,숫자,특수기호 중 2가지 이상 조합하여 10자리 이상 16자리 이하입니다.</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호 확인</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"password\" id=\"pwdConfirm\" name=\"pwdConfirm\" required>\r\n");
      out.write("						<p class=\"error\" id=\"pwdConfirmError\">비밀번호가 일치하지 않습니다.</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이메일 주소</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("						<p class=\"error\" id=\"emailError\">올바른 이메일 형식으로 입력해주세요.</p>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>우편번호</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<input type=\"text\" name=\"zipcode\" id=\"postcode\" placeholder=\"우편번호\" size=\"5\" readonly>\r\n");
      out.write("						<input type=\"button\" onclick=\"execKakaoPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("						<input type=\"text\" name=\"address1\" id=\"address\" placeholder=\"주소\" size=\"45\" readonly><br>\r\n");
      out.write("						<input type=\"text\" name=\"address2\" id=\"detailAddress\" placeholder=\"상세주소\" size=\"45\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>취미</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" value=\"인터넷\">인터넷</label>\r\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" value=\"여행\">여행</label>\r\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" value=\"게임\">게임</label>\r\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" value=\"영화\">영화</label>\r\n");
      out.write("						<label><input type=\"checkbox\" name=\"hobby\" value=\"운동\">운동</label>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>직업</th>\r\n");
      out.write("					<td><select name=job required>\r\n");
      out.write("							<option value=\"0\" selected>선택하세요.\r\n");
      out.write("							<option value=\"회사원\">회사원\r\n");
      out.write("							<option value=\"연구전문직\">연구전문직\r\n");
      out.write("							<option value=\"교수학생\">교수학생\r\n");
      out.write("							<option value=\"일반자영업\">일반자영업\r\n");
      out.write("							<option value=\"공무원\">공무원\r\n");
      out.write("							<option value=\"의료인\">의료인\r\n");
      out.write("							<option value=\"법조인\">법조인\r\n");
      out.write("							<option value=\"종교,언론,에술인\">종교.언론/예술인\r\n");
      out.write("							<option value=\"농,축,수산,광업인\">농/축/수산/광업인\r\n");
      out.write("							<option value=\"주부\">주부\r\n");
      out.write("							<option value=\"무직\">무직\r\n");
      out.write("							<option value=\"기타\">기타\r\n");
      out.write("					</select></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<button id=\"memberBtn\" disabled>회원가입</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://t1.kakaocdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		const path = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("	</script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/member.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
