# 1. 프로젝트명
spring.application.name=sb.member.ex01
# 2. 포트 설정: localhost:8080 일때는 생략 가능
server.port=${PORT:8080}
# 3. View Resolver 설정 (JSP 관련)
# JSP 대신 타임리프를 사용할 경우 생략
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
# 4. MySQL 데이터베이스 연결 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 5. Spring Boot DevTools 설정
spring.devtools.livereload.enabled=true